const quotes=[
{"quotes":"Believe you can, and you're halfway there.","author":"Theodore Roosevel"},
{"quotes":"The future belongs to those who believe in the beauty of their dreams." ,"author":"leanor Roosevelt"},
{"quotes":"Don't watch the clock; do what it does. Keep going." ,"author":"am Levenson"},
{"quotes":"Success is not final, failure is not fatal: It is the courage to continue that counts." ,"author":"inston Churchill"},
{"quotes":"The only way to do great work is to love what you do." ,"author":"teve Jobs"},
{"quotes":"The harder you work for something, the greater you'll feel when you achieve it." ,"author":"unknown"},
{"quotes":"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." ,"author":"hristian D. Larson"},
{"quotes":"Your time is limited, don't waste it living someone else's life." ,"author":"teve Jobs"},
{"quotes":"The best way to predict the future is to create it." ,"author":"eter Drucker"},
{"quotes":"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." ,"author":"lbert Schweitzer"},
{"quotes":"The secret to getting ahead is getting started." ,"author":"ark Twain"},
{"quotes":"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart." ,"author":"oy T. Bennett"},
{"quotes":"The only limit to our realization of tomorrow will be our doubts of today." ,"author":"ranklin D. Roosevelt"},
{"quotes":"The only person you should try to be better than is the person you were yesterday." ,"author":"nknown"},
{"quotes":"You don't have to be great to start, but you have to start to be great." ,"author":"ig Ziglar"},
{"quotes":"The future starts today, not tomorrow." ,"author":"ope John Paul II"},
{"quotes":"The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it." ,"author":"ichelangelo"},
{"quotes":"You are never too old to set another goal or to dream a new dream." ,"author":".S. Lewis"},
{"quotes":"Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this." ,"author":"hantal Sutherland"},
{"quotes":"If you want to achieve greatness, stop asking for permission." ,"author":"nonymous"},
{"quotes":"The only way to do something great is to love what you do." ,"author":"teve Jobs"},
{"quotes":"I can't change the direction of the wind, but I can adjust my sails to always reach my destination." ,"author":"immy Dean"},
{"quotes":"Success is not just about making money. It's about making a difference." ,"author":"nknown"},
{"quotes":"Don't be afraid to give up the good to go for the great." ,"author":"ohn D. Rockefeller"},
{"quotes":"Every accomplishment starts with the decision to try." ,"author":"unknown"},
{"quotes":"Challenges are what make life interesting and overcoming them is what makes life meaningful." ,"author":"oshua J. Marine"},
{"quotes":"You miss 100% of the shots you don't take." ,"author":"ayne Gretzky"},
{"quotes":"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." ,"author":"teve Jobs"},
{"quotes":"Success is not in what you have, but who you are." ,"author":"o Bennett"},
{"quotes":"Life is 10% what happens to us and 90% how we react to it." ,"author":"harles R. Swindoll"},
{"quotes":"In the middle of every difficulty lies opportunity." ,"author":"lbert Einstein"},
{"quotes":"The distance between your dreams and reality is called action." ,"author":"nknown"},
{"quotes":"The only place where success comes before work is in the dictionary." ,"author":"idal Sassoon"},
{"quotes":"Do what you can, where you are, with what you have." ,"author":"heodore Roosevelt"},
{"quotes":"The road to success is always under construction." ,"author":"ily Tomlin"},
{"quotes":"The mind is everything. What you think, you become." ,"author":"uddha"},
{"quotes":"It does not matter how slowly you go, as long as you do not stop." ,"author":"onfucius"},
{"quotes":"Success is not in what you have, but who you are." ,"author":"nknown"},
{"quotes":"If you want to achieve greatness, stop asking for permission." ,"author":"nknown"},
{"quotes":"It's not about how hard you hit. It's about how hard you can get hit and keep moving forward." ,"author":"ocky Balboa"},
{"quotes":"You are never too old to set another goal or to dream a new dream." ,"author":".S. Lewis"},
{"quotes":"The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks." ,"author":"ark Zuckerberg"},
{"quotes":"Believe you can and you're halfway there." ,"author":"heodore Roosevelt"},
{"quotes":"The only limit to our realization of tomorrow will be our doubts of today." ,"author":"ranklin D. Roosevelt"},
{"quotes":"Your time is limited, so don't waste it living someone else's life." ,"author":"teve Jobs"},
{"quotes":"The best way to predict the future is to create it." ,"author":"eter Drucker"},
{"quotes":"The only person you are destined to become is the person you decide to be." ,"author":"alph Waldo Emerson"},
{"quotes":"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." ,"author":"hristian D. Larson"},
{"quotes":"Don't watch the clock; do what it does. Keep going." ,"author":"am Levenson"},
{"quotes":"Success is not final, failure is not fatal: It is the courage to continue that counts." ,"author":"inston Churchill"},
{"quotes":"The future belongs to those who believe in the beauty of their dreams." ,"author":"leanor Roosevelt"},
{"quotes":"The harder you work for something, the greater you'll feel when you achieve it." ,"author":"nknown"},
{"quotes":"The secret to getting ahead is getting started." ,"author":"ark Twain"},
{"quotes":"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart." ,"author":"oy T. Bennett"},
{"quotes":"The only way to do great work is to love what you do." ,"author":"teve Jobs"},
{"quotes":"The future starts today, not tomorrow." ,"author":"ope John Paul II"},
{"quotes":"The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it." ,"author":"ichelangelo"},
{"quotes":"You don't have to be great to start, but you have to start to be great." ,"author":"ig Ziglar"},
{"quotes":"You are never too old to set another goal or to dream a new dream." ,"author":".S. Lewis"},
{"quotes":"If you want to achieve greatness, stop asking for permission." ,"author":"nonymous"},
{"quotes":"The only way to do something great is to love what you do." ,"author":"teve Jobs"},
{"quotes":"I can't change the direction of the wind, but I can adjust my sails to always reach my destination." ,"author":"immy Dean"},
{"quotes":"Success is not just about making money. It's about making a difference." ,"author":"nknown"},
{"quotes":"Don't be afraid to give up the good to go for the great." ,"author":"ohn D. Rockefeller"},
{"quotes":"Every accomplishment starts with the decision to try." ,"author":"nknown"},
{"quotes":"Challenges are what make life interesting and overcoming them is what makes life meaningful." ,"author":"oshua J. Marine"},
{"quotes":"You miss 100% of the shots you don't take." ,"author":"ayne Gretzky"},
{"quotes":"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." ,"author":"teve Jobs"},
{"quotes":"Success is not in what you have, but who you are." ,"author":"o Bennett"},
{"quotes":"Life is 10% what happens to us and 90% how we react to it." ,"author":"harles R. Swindoll"},
{"quotes":"In the middle of every difficulty lies opportunity." ,"author":"lbert Einstein"},
{"quotes":"The distance between your dreams and reality is called action." ,"author":"nknown"},
{"quotes":"The only place where success comes before work is in the dictionary." ,"author":"idal Sassoon"},
{"quotes":"Do what you can, where you are, with what you have." ,"author":"heodore Roosevelt"},
{"quotes":"The road to success is always under construction." ,"author":"ily Tomlin"},
{"quotes":"The mind is everything. What you think, you become." ,"author":"uddha"},
{"quotes":"It does not matter how slowly you go, as long as you do not stop." ,"author":"onfucius"},
{"quotes":"Success usually comes to those who are too busy to be looking for it." ,"author":"enry David Thoreau"},
{"quotes":"The only way to do great work is to love what you do." ,"author":"teve Jobs"},
{"quotes":"The best time to plant a tree was 20 years ago. The second best time is now." ,"author":"hinese Proverb"},
{"quotes":"The only person you should try to be better than is the person you were yesterday." ,"author":"nknown"},
{"quotes":"The harder you work for something, the greater you'll feel when you achieve it." ,"author":"nknown"},
{"quotes":"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." ,"author":"hristian D. Larson"},
{"quotes":"Your time is limited, don't waste it living someone else's life." ,"author":"teve Jobs"},
{"quotes":"The best way to predict the future is to create it." ,"author":"eter Drucker"},
{"quotes":"The only limit to our realization of tomorrow will be our doubts of today." ,"author":"ranklin D. Roosevelt"},
{"quotes":"The only place where success comes before work is in the dictionary." ,"author":"idal Sassoon"},
{"quotes":"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart." ,"author":"oy T. Bennett"},
{"quotes":"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." ,"author":"lbert Schweitzer"},
{"quotes":"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." ,"author":"teve Jobs"},
{"quotes":"The future belongs to those who believe in the beauty of their dreams." ,"author":"leanor Roosevelt"},
{"quotes":"The only way to do great work is to love what you do." ,"author":"teve Jobs"},
{"quotes":"The best way to predict the future is to create it." ,"author":"eter Drucker"},
{"quotes":"Don't watch the clock; do what it does. Keep going." ,"author":"am Levenson"},
{"quotes":"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." ,"author":"hristian D. Larson"},
{"quotes":"Your time is limited, don't waste it living someone else's life." ,"author":"teve Jobs"},
{"quotes":"The only limit to our realization of tomorrow will be our doubts of today." ,"author":"ranklin D. Roosevelt"},
{"quotes":"You don't have to be great to start, but you have to start to be great." ,"author":"ig Ziglar"},
{"quotes":"Success is not in what you have, but who you are." ,"author":"o Bennett"},
{"quotes":"If you want to achieve greatness, stop asking for permission." ,"author":"anonymous"
}      
]

module.exports=quotes;